version: "3.8"

services:
  db:
    image: postgres:14
    container_name: blog-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JAVA
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"   # host 5434 → container 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloguser -d blogdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-management
    container_name: blog-management
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: JAVA
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 4343
    ports:
      - "8080:4343"

volumes:
  postgres-data:
